-------------------------------------------------------------------------------
Test set: hello.ApplicationTests
-------------------------------------------------------------------------------
Tests run: 7, Failures: 1, Errors: 1, Skipped: 0, Time elapsed: 10.628 s <<< FAILURE! - in hello.ApplicationTests
shouldReturnRepositoryIndex(hello.ApplicationTests)  Time elapsed: 0.127 s  <<< FAILURE!
java.lang.AssertionError: No value at JSON path "$._links.people"
	at hello.ApplicationTests.shouldReturnRepositoryIndex(ApplicationTests.java:54)
Caused by: com.jayway.jsonpath.PathNotFoundException: Expected to find an object with property ['_links'] in path $ but found 'java.lang.String'. This is not a json object according to the JsonProvider: 'com.jayway.jsonpath.spi.json.JsonSmartJsonProvider'.
	at hello.ApplicationTests.shouldReturnRepositoryIndex(ApplicationTests.java:54)

shouldPartiallyUpdateEntity(hello.ApplicationTests)  Time elapsed: 0.074 s  <<< ERROR!
org.springframework.dao.DataIntegrityViolationException: 
could not execute statement; SQL [n/a]; constraint ["FKS4VMNBRF34RSNQCDIEKREEQ1F: PUBLIC.NODE_RESPONSIBLE FOREIGN KEY(RESPONSIBLE_ID) REFERENCES PUBLIC.PERSON(ID) (6)"; SQL statement:
delete from person where id=? [23503-197]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
	at hello.ApplicationTests.deleteAllBeforeTests(ApplicationTests.java:48)
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
	at hello.ApplicationTests.deleteAllBeforeTests(ApplicationTests.java:48)
Caused by: org.h2.jdbc.JdbcSQLException: 
Referential integrity constraint violation: "FKS4VMNBRF34RSNQCDIEKREEQ1F: PUBLIC.NODE_RESPONSIBLE FOREIGN KEY(RESPONSIBLE_ID) REFERENCES PUBLIC.PERSON(ID) (6)"; SQL statement:
delete from person where id=? [23503-197]
	at hello.ApplicationTests.deleteAllBeforeTests(ApplicationTests.java:48)

